In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
kp2020 = pd.read_csv('data/KP2020.csv', encoding='cp949')
print(kp2020.shape)
display(kp2020.head())

(77077, 10)

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
0,충남청,20/12/01 01:43:07.000000000,19,10,305,1.0,충청남도 보령시 궁촌동(행정:대천4동) 369,126.598345,36.341537,Y
1,대전청,20/12/01 02:05:04.000000000,13,10,601,3.0,NaN,127.404663,36.341685,NaN
2,대전청,20/12/01 02:06:52.000000000,13,10,601,1.0,NaN,127.404663,36.341685,NaN
3,충남청,20/12/01 02:37:25.000000000,19,10,606,3.0,충청남도 보령시 천북면 하만리 628-10,126.524980,36.474390,N
4,충남청,20/12/01 08:17:50.000000000,19,10,401,2.0,충청남도 천안시 서북구 성정동(행정:성정2동) 1259,127.137160,36.826718,NaN

In [3]:
kp2021 = pd.read_csv('data/KP2021.csv', encoding='cp949')
print(kp2021.shape)
display(kp2021.head())

(2594060, 10)

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
0,대전청,21/03/07 00:00:01.000000000,13,10,604,3.0,대전광역시 서구 둔산동 1122,127.373676,36.350975,Y
1,대전청,21/03/07 00:02:13.000000000,13,10,201,1.0,대전광역시 유성구 상대동(원신흥동) 469-9,127.339018,36.347420,NaN
2,대전청,21/03/07 00:00:33.000000000,13,10,601,3.0,NaN,127.404663,36.341685,NaN
3,대전청,21/03/07 00:01:18.000000000,13,10,601,3.0,NaN,127.404663,36.341685,NaN
4,대전청,21/03/07 00:01:43.000000000,13,10,308,1.0,대전광역시 중구 선화동 141-16,127.420455,36.330413,NaN

In [4]:
npa2020 = pd.read_csv('data/NPA2020.csv', encoding='cp949')
print(npa2020.shape)
display(npa2020.head())

(1178244, 10)

,RECV_CPLT_DT,RECV_CPLT_TM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_OLD_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
0,20200101,7,13,10,501,2,대전광역시 중구 목동(행정:목동) 360,127.409270,36.333010,Y
1,20200101,132,13,10,501,1,대전광역시 중구 대흥동(대흥동) 499-1,127.421295,36.325575,NaN
2,20200101,39,13,10,501,1,NaN,127.404663,36.341685,NaN
3,20200101,110,13,10,601,3,NaN,0.000000,0.000000,NaN
4,20200101,342,13,10,601,1,NaN,127.404663,36.341685,NaN

## kp 보이스피싱 데이터 병합

In [5]:
kp215_2020 = kp2020[kp2020['EVT_CL_CD'] == 215]
kp215_2020.head(2)

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
333,충남청,20/12/01 15:06:38.000000000,19,10,215,1.0,충청남도 아산시 온천동(온양1동) 1556(신학산텔레콤),127.001705,36.786898,NaN
360,충남청,20/12/01 14:53:20.000000000,19,10,215,2.0,충청남도 공주시 우성면 동대리(행정:우성면) 173,127.052120,36.470196,NaN

In [6]:
kp215_2021 =  kp2021[kp2021['EVT_CL_CD'] == 215]
kp215_2021.head(2)

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
305,충남청,21/01/01 15:29:24.000000000,19,10,215,1.0,충청남도 보령시 청라면 나원리(행정:청라면) 910-7,126.67366,36.389902,Y
361,충남청,21/01/01 16:15:21.000000000,19,10,215,1.0,충청남도 보령시 청라면 나원리(행정:청라면) 910-7,126.67366,36.389902,Y

In [7]:
kp215 = pd.concat([kp215_2020, kp215_2021], ignore_index=True)
kp215.head()

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
0,충남청,20/12/01 15:06:38.000000000,19,10,215,1.0,충청남도 아산시 온천동(온양1동) 1556(신학산텔레콤),127.001705,36.786898,NaN
1,충남청,20/12/01 14:53:20.000000000,19,10,215,2.0,충청남도 공주시 우성면 동대리(행정:우성면) 173,127.052120,36.470196,NaN
2,충남청,20/12/01 11:15:43.000000000,19,10,215,2.0,충청남도 공주시 반포면 공암리(행정:반포면),127.251164,36.395766,NaN
3,충남청,20/12/01 13:08:09.000000000,19,10,215,1.0,충청남도 아산시 음봉면 삼거리(행정:음봉면) 203-3,127.012487,36.849074,NaN
4,충남청,20/12/01 14:00:07.000000000,19,10,215,1.0,충청남도 천안시 동남구 다가동(일봉동) 354-1(농협중앙회봉명지점),127.140700,36.802345,NaN

## kp 데이터 전처리

In [8]:
kp215['RECV_CPLT_DM'] = kp215['RECV_CPLT_DM'].apply(lambda x: pd.to_datetime(x.split('.')[0], format='%y/%m/%d %H:%M:%S'))

In [9]:
kp215.head()

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
0,충남청,2020-12-01 15:06:38,19,10,215,1.0,충청남도 아산시 온천동(온양1동) 1556(신학산텔레콤),127.001705,36.786898,NaN
1,충남청,2020-12-01 14:53:20,19,10,215,2.0,충청남도 공주시 우성면 동대리(행정:우성면) 173,127.052120,36.470196,NaN
2,충남청,2020-12-01 11:15:43,19,10,215,2.0,충청남도 공주시 반포면 공암리(행정:반포면),127.251164,36.395766,NaN
3,충남청,2020-12-01 13:08:09,19,10,215,1.0,충청남도 아산시 음봉면 삼거리(행정:음봉면) 203-3,127.012487,36.849074,NaN
4,충남청,2020-12-01 14:00:07,19,10,215,1.0,충청남도 천안시 동남구 다가동(일봉동) 354-1(농협중앙회봉명지점),127.140700,36.802345,NaN

## npa 데이터 전처리

In [10]:
npa215 = npa2020[npa2020['EVT_CL_CD']==215]
npa215.head(2)

,RECV_CPLT_DT,RECV_CPLT_TM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_OLD_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
3221,20200102,150928,13,10,215,2,NaN,127.404663,36.341685,NaN
3408,20200102,123351,13,10,215,1,대전광역시 동구 용전동(행정:용전동) 220,127.430177,36.336496,NaN

In [11]:
npa215.insert(0, 'RECV_DEPT_NM', np.nan)
npa215.loc[npa215['NPA_CL'] == 13, 'RECV_DEPT_NM'] = '대전청'
npa215.loc[npa215['NPA_CL'] == 19, 'RECV_DEPT_NM'] = '충남청'

In [12]:
npa215.head(2)

,RECV_DEPT_NM,RECV_CPLT_DT,RECV_CPLT_TM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_OLD_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
3221,대전청,20200102,150928,13,10,215,2,NaN,127.404663,36.341685,NaN
3408,대전청,20200102,123351,13,10,215,1,대전광역시 동구 용전동(행정:용전동) 220,127.430177,36.336496,NaN

In [13]:
npa215['RECV_CPLT_TM'] = npa215['RECV_CPLT_TM'].astype('str')
npa215['RECV_CPLT_TM'] = npa215['RECV_CPLT_TM'].str.rjust(width=6, fillchar='0')

In [14]:
npa215['RECV_CPLT_DM'] = npa215['RECV_CPLT_DT'].astype('str') + npa215['RECV_CPLT_TM']

In [15]:
npa215['RECV_CPLT_DM'] = pd.to_datetime(npa215['RECV_CPLT_DM'])

In [16]:
npa215.drop('RECV_CPLT_DT', axis=1, inplace=True)
npa215.drop('RECV_CPLT_TM', axis=1, inplace=True)
npa215 = npa215.rename(columns={'HPPN_OLD_ADDR':'HPPN_PNU_ADDR'},)

## kp, npa 병합

In [17]:
kpa215 = pd.concat([kp215, npa215], ignore_index=True)
kpa215.head(2)

,RECV_DEPT_NM,RECV_CPLT_DM,NPA_CL,EVT_STAT_CD,EVT_CL_CD,RPTER_SEX,HPPN_PNU_ADDR,HPPN_X,HPPN_Y,SME_EVT_YN
0,충남청,2020-12-01 15:06:38,19,10,215,1.0,충청남도 아산시 온천동(온양1동) 1556(신학산텔레콤),127.001705,36.786898,NaN
1,충남청,2020-12-01 14:53:20,19,10,215,2.0,충청남도 공주시 우성면 동대리(행정:우성면) 173,127.052120,36.470196,NaN

In [18]:
kpa215.drop('EVT_CL_CD',axis=1, inplace=True)
kpa215 = kpa215.rename(columns={'RECV_DEPT_NM':'접수부서', 'RECV_CPLT_DM':'접수완료일시', 'NPA_CL':'경찰청구분', 'EVT_STAT_CD':'사건상태', 'RPTER_SEX':'성별', 'HPPN_PNU_ADDR':'발생지점','HPPN_X':'발생좌표X', 'HPPN_Y':'발생좌표Y', 'SME_EVT_YN':'동일사건여부'})

## kpa 변수명 변경

In [19]:
codebook = pd.read_excel('data/codeBook_v3.xlsx')

In [20]:
npa_cl = dict(zip(codebook.loc[codebook['컬럼명'] == 'NPA_CL']['코드값'].astype(str).tolist(), codebook.loc[codebook['컬럼명'] == 'NPA_CL']['코드명'].tolist()))

In [21]:
kpa215['경찰청구분'] = kpa215['경찰청구분'].astype('str').map(npa_cl)

In [22]:
evt_st = dict(zip(codebook.loc[codebook['컬럼명'] == 'EVT_STAT_CD']['코드값'].astype(str).tolist(), codebook.loc[codebook['컬럼명'] == 'EVT_STAT_CD']['코드명'].tolist()))

In [26]:
kpa215['사건상태'] = kpa215['사건상태'].astype('str').map(evt_st)

In [60]:
def sex(n):
    if n == 1:
        return '남성'
    elif n == 2:
        return '여성'
    else:
        return '불상'

In [61]:
kpa215['성별'] = kpa215['성별'].map(sex)

## 데이터 저장

In [66]:
kpa215.to_csv('data/kpa215.csv', index=False)

### 데이터 정리
- kp는 대전 세종 충남 지역의 사건들을 모아놨다.('충남청', '대전청', '2지구대(충남)', '남대전지구대', '대전대덕', '대전동부', '대전파출소', '대전역지구대', '대전중부', '대전둔산', '대전서부', '서대전지구대', '대전유성', '세종로파출소', '세종', '세종청')
- npa는 대전청과 충남청 사건들만 모아놨다.
- 취급하는 사건의 갯수는 npa 데이터가 더 많다.
- 보이스 피싱 사건만 두고 봤을 때도 npa 데이터가 훨씬 많다 왜?
- 시간순 정렬
- npa는 2020년 1월\~11월 / kp는 2020년 12월, 2021년 3월\~ 2023년 1월